#pragma once
#include <Windows.h>
#include <string>
#include <fstream>
#include <iterator>
#include <vector>
#include <sstream>
#include <stdlib.h>
#include <math.h>
#include "Main.h"
#include "Win32App.h"
#include "Showable.h"
#include "Actor.h"
#include "Bitmap.h"
